name: osmc

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]

    steps: 
        - uses: actions/checkout@v2
          with:
            submodules: true

          
        - uses: lukka/get-cmake@latest
        
        - name: Set up CLANG
          if: matrix.os == 'ubuntu-latest'
          uses: egor-tensin/setup-clang@v1
          with:
            version: latest
            platform: x64
        - name: CLANG to path
          if: matrix.os == 'windows-latest'
          run: |
            echo "::add-path::C:\msys64\mingw64\bin"

        - name: run cmake
          run: |
            cmake .

        - name: run make
          run: |
            make
          


