name: osmc

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]

    steps: 
        - uses: actions/checkout@v2
          with:
            submodules: true

          
        - uses: lukka/get-cmake@latest
        
        - name: Set up CLANG
          if: matrix.os == 'ubuntu-latest'
          uses: egor-tensin/setup-clang@v1
          with:
            version: latest
            platform: x64

        - name: CLANG to path WINDOWS
          if: matrix.os == 'windows-latest'
##https://stackoverflow.com/a/64831469
          run: |
            echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: run cmake non-windows
          if: matrix.os != 'windows-latest'
          run: |
            cmake .

        - name: run cmake windows
          if: matrix.os == 'windows-latest'
          env:
            CC: clang
            CXX: clang++
          run: |
            cmake .

        - name: run make NON WINDOWS
          if: matrix.os != 'windows-latest'
          run: |
            make

        - name: run ninja windows
          if: matrix.os == 'windows-latest' 
          run: |
            ninja
          


