name: osmc

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest , macos-latest ]

    steps: 
        - uses: actions/checkout@v2
          with:
            submodules: true

        - name: Set up CLANG
          if: matrix.os != 'macos-latest'
          uses: egor-tensin/setup-clang@v1
          with:
            version: latest
            platform: x64
          
        - uses: lukka/get-cmake@latest

        - name: run cmake
          run: |
            cmake .

        - name: run make
          run: |
            make
          


